const AppActionTypes = {
    FETCH_SEARCH_START: 'FETCH_SEARCH_START',
    FETCH_SEARCH_SUCCESS: 'FETCH_SEARCH_SUCCESS',
    FETCH_SEARCH_FAILURE: 'FETCH_SEARCH_FAILURE',
    CLEAR_TIME_STAMP : 'CLEAR_TIME_STAMP',
    FILL_ANALYZED_RESULTS:'FILL_ANALYZED_RESULTS'
  };
  
  export default AppActionTypes;
  